### PR TITLE
fix: add paths to zon file

### PR DESCRIPTION
**Pull request by danbanta**
Added paths to zon file

### CODE REVIEW

**Comment by ikskuh** [comment]
What exactly does that change do and will it compile with Zig 0.11?

**Comment by danbanta** [comment]
@MasterQ32 I apologize. I did not see where `regz` is compiled against Zig `0.11` only. This change is because I am on Zig `main` branch. I will test with Zig `0.11` and see if the PR should be closed. Thank you for your patience.

**Comment by ikskuh** [comment]
Not sure we're actually having a huge statement that ZEG is sticking to tagged releases from 0.11 on, but we do :)

**Comment by kassane** [comment]
> What exactly does that change do and will it compile with Zig 0.11?

zig 0.11.0 ignore `.path = .{""},`

**Pull request merged**
